version: 1.2
workflows:
  - name: ReadStats
    subclass: WDL
    description: Simple stats about reads in one gzipped FASTQ file. Simplified from HPP workflow https://github.com/human-pangenomics/hpp_production_workflows/blob/master/QC/wdl/tasks/read_stats.wdl (one file input, must be gzipped FASTQ, but all in one task)
    primaryDescriptorPath: /read_stats/workflow.wdl
    testParameterFiles:
      - /read_stats/inputs.json
    branches:
      - master
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
  - name: ChimeraStats
    subclass: WDL
    description: Estimate the amount of chimeric (long) reads. Uses https://github.com/rlorigro/Liger2LiGer.
    primaryDescriptorPath: /chimera_stats/workflow.wdl
    testParameterFiles:
      - /chimera_stats/inputs.json
    branches:
      - master
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
  - name: AlignStats
    subclass: WDL
    description: Compute the distribution of alignment identity using wambam https://github.com/rlorigro/wambam
    primaryDescriptorPath: /align_stats/workflow.wdl
    testParameterFiles:
      - /align_stats/inputs.json
    branches:
      - master
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
  - name: GuppyBasecalling
    subclass: WDL
    description: Basecall a fast5 file using Guppy. This workflow was adapted from the scatterGuppy.wdl in the human-pangenomics/hpp_production_workflows repo (https://github.com/human-pangenomics/hpp_production_workflows/blob/master/data_processing/wdl/scatterGuppy.wdl). It was originally written by Jimin Park (jpark621@ucsc.edu).
    primaryDescriptorPath: /guppy_basecalling/workflow.wdl
    testParameterFiles:
      - /guppy_basecalling/inputs.json
    branches:
      - master
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
  - name: SubsetFastqByQscore
    subclass: WDL
    description: Subset a fastq for reads with a minimum basecalling qscore. 
    primaryDescriptorPath: /read_subset_qscore/workflow.wdl
    testParameterFiles:
      - /read_subset_qscore/inputs.json
    branches:
      - master
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
  - name: QuastQC
    subclass: WDL
    description: Run QUAST to get QC metrics on an assembly slightly tweaked from https://dockstore.org/workflows/github.com/human-pangenomics/hpp_production_workflows/Quast to allow for an input array of fasta files (that will be concatenated).
    primaryDescriptorPath: /quast_qc/workflow.wdl
    testParameterFiles:
      - /quast_qc/inputs.json
    branches:
      - master
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
  - name: AsmGene
    subclass: WDL
    description: Same as github.com/human-pangenomics/hpp_production_workflows/Asmgene but with defined output (e.g. for Terra table)
    primaryDescriptorPath: /asmgene/workflow.wdl
    branches:
      - master
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
  - name: IndexBam
    subclass: WDL
    description: Index a BAM with samtools
    primaryDescriptorPath: /index_bam/workflow.wdl
    branches:
      - master
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
  - name: AddUnmappedGamBam
    subclass: WDL
    description: Index a BAM with samtools
    primaryDescriptorPath: /add_unmapped_gam_bam/workflow.wdl
    branches:
      - master
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
