version: 1.2
workflows:
  - name: ReadStats
    subclass: WDL
    description: Simple stats about reads in one gzipped FASTQ file. Simplified from HPP workflow https://github.com/human-pangenomics/hpp_production_workflows/blob/master/QC/wdl/tasks/read_stats.wdl (one file input, must be gzipped FASTQ, but all in one task)
    primaryDescriptorPath: /read_stats/workflow.wdl
    testParameterFiles:
      - /read_stats/inputs.json
    branches:
      - master
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
  - name: ChimeraStats
    subclass: WDL
    description: Estimate the amount of chimeric (long) reads. Uses https://github.com/rlorigro/Liger2LiGer.
    primaryDescriptorPath: /chimera_stats/workflow.wdl
    testParameterFiles:
      - /chimera_stats/inputs.json
    branches:
      - master
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
